@echo off
rem ---- installation ----

rem refresh path
for /f "tokens=3*" %%A in ('reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path') do set syspath=%%A%%B
for /f "tokens=3*" %%A in ('reg query "HKCU\Environment" /v Path') do set userpath=%%A%%B
set PATH=%userpath%;%syspath%

rem Check if Node.js is installed
where node >nul 2>&1
echo %errorlevel%
rem If Node.js is not found, the command will return a non-zero exit code
if %errorlevel% neq 0 (
    echo Node.js is not installed. Installing...
    
    rem Attempt to install Node.js using winget
    winget install -e --accept-source-agreements --accept-package-agreements --id OpenJS.NodeJS
    
    rem Check if winget install was successful
) else (
    echo Node.js is already installed.
)
rem Check if cloudflared is in the system PATH
where cloudflared >nul 2>&1
echo %errorlevel%
rem If cloudflared is not found, the command will return a non-zero exit code
if %errorlevel% neq 0 (
    echo cloudflared is not installed. Installing...
    
    rem Attempt to install cloudflared using winget
    winget install -e --accept-source-agreements --accept-package-agreements --id Cloudflare.cloudflared
    
    rem Check if winget install was successful
) else (
    echo cloudflared is already installed.
)




rem refresh path, again
for /f "tokens=3*" %%A in ('reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path') do set syspath=%%A%%B
for /f "tokens=3*" %%A in ('reg query "HKCU\Environment" /v Path') do set userpath=%%A%%B
set PATH=%userpath%;%syspath%

if exist .env (
    echo .env file detected.
) else (
    echo .env file not found. Creating .env file...

    echo Create/Get the discord application of your choosing and input its client id and secret [https://discord.com/developers/applications]

    rem Enable delayed expansion to use variables after they are set
    setlocal enabledelayedexpansion

    rem Prompt the user for input
    echo Enter the VITE_DISCORD_CLIENT_ID:
    set /p VITE_DISCORD_CLIENT_ID=
    echo Enter the DISCORD_CLIENT_SECRET:
    set /p DISCORD_CLIENT_SECRET=

    rem Write the values to the .env file using delayed expansion
    echo VITE_DISCORD_CLIENT_ID=!VITE_DISCORD_CLIENT_ID! > .env
    echo DISCORD_CLIENT_SECRET=!DISCORD_CLIENT_SECRET! >> .env

    rem Confirm that the .env file has been created
    echo .env file has been created with the provided values.

    endlocal
)


cd ./client
call npm i
cd ../server
call npm i

rem ---- execution ----

cd ../client
start cmd /k "npm run dev"
cd ../server
start cmd /k "npm run dev"
cd ../
tasklist /FI "IMAGENAME eq cloudflared.exe" 2>NUL | find /I "cloudflared.exe" >NUL
echo %ERRORLEVEL%
if %ERRORLEVEL% NEQ 0 (
    :: If cloudflared is not running, start the tunnel
    start cmd /k "cloudflared tunnel --url http://localhost:5173"
) else (
    echo cloudflared tunnel is already running.
)


echo Now, setup the rest of the discord application as [https://discord.com/developers/docs/activities/building-an-activity] shows, and get the ip generated by cloudflare and modify vite.config.js accordingly